spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: /sql/schema-dev.sql
    data: /sql/data-dev.sql
  jpa:
    hibernate:
      ddl-auto: update